// ============================================================
// data.ts - 绿意家居产品数据（8大分类，60+ 款产品）
// Design: Urban Oasis - Deep forest green + warm cream
// ============================================================

export interface Product {
  id: string;
  sku: string;
  name: string;
  subtitle: string;
  nameEn: string;
  price: number;
  originalPrice?: number;
  category: string;
  subcategory: string;
  tags: string[];
  image: string;
  rating: number;
  reviews: number;
  description: string;
  features: string[];
  size: string;
  height: string;
  material: string;
  color: string;
  isHot?: boolean;
  isNew?: boolean;
  inStock?: boolean;
  customizable?: boolean;
}

export interface Category {
  id: string;
  name: string;
  icon: string;
  count: number;
  description: string;
}

export interface Review {
  id: string;
  author: string;
  avatar: string;
  rating: number;
  content: string;
  date: string;
  product: string;
  verified: boolean;
}

// 使用生成的图片 URL
const HERO_BG = "https://d2xsxph8kpxj0f.cloudfront.net/310519663392852100/CD7tjTbceR5unCtzt9q9hX/hero-bg-evb8FWSHHnF5QdafQkmvs6.webp";
const MONSTERA = "https://d2xsxph8kpxj0f.cloudfront.net/310519663392852100/CD7tjTbceR5unCtzt9q9hX/product-monstera-eGzsi5GCaR9vwG6uNQVs7a.webp";
const OLIVE = "https://d2xsxph8kpxj0f.cloudfront.net/310519663392852100/CD7tjTbceR5unCtzt9q9hX/product-olive-tree-6cqVJhT9L5FgXQZYKpWm2a.webp";
const SUCCULENT = "https://d2xsxph8kpxj0f.cloudfront.net/310519663392852100/CD7tjTbceR5unCtzt9q9hX/product-succulent-8nJkL2mPqRsT3uVwXyZ1a.webp";
const OFFICE = "https://d2xsxph8kpxj0f.cloudfront.net/310519663392852100/CD7tjTbceR5unCtzt9q9hX/office-scene-CTrfaDLtTmxXRerD8KfkKW.webp";

export const categories: Category[] = [
  { id: "all", name: "全部产品", icon: "🌿", count: 60, description: "所有仿真绿植" },
  { id: "mini-potted", name: "小型花卉盆栽", icon: "🌱", count: 12, description: "精致小巧，适合办公桌、书架、窗台" },
  { id: "medium-potted", name: "中型盆栽", icon: "🪴", count: 15, description: "客厅、卧室、餐厅的完美装饰" },
  { id: "large-floor", name: "大型落地树", icon: "🌳", count: 18, description: "气势恢宏，打造空间主角" },
  { id: "flower-arrangement", name: "花瓶插花系列", icon: "💐", count: 10, description: "高端花艺，提升生活品质" },
  { id: "commercial-trees", name: "商业用高大乔木", icon: "🏢", count: 14, description: "酒店、商场、展厅专用" },
  { id: "plant-sculpture", name: "植物雕塑系列", icon: "🎨", count: 8, description: "艺术与绿植的完美融合" },
  { id: "commercial-display", name: "商业布展方案", icon: "🏗️", count: 5, description: "专业团队定制设计" },
];

export const products: Product[] = [
  // ========== 小型花卉盆栽 ==========
  {
    id: "655697",
    sku: "655697",
    name: "迷你榕树 - 高级版",
    subtitle: "精心打造，叶片逼真度99%",
    nameEn: "Mini Ficus Tree Premium",
    price: 189,
    originalPrice: 249,
    category: "mini-potted",
    subcategory: "ficus-series",
    tags: ["榕树", "迷你", "高级"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663392852100/CD7tjTbceR5unCtzt9q9hX/HpPgI42Q10ry_a5f05377.jpg",
    rating: 4.8,
    reviews: 328,
    description: "精心打造的迷你榕树，采用高分子仿真技术，叶片逼真度达99%。适合客厅角落、办公室前台等空间。",
    features: ["高度仿真", "防晒防褪色", "易清洁", "无需浇水"],
    size: "30cm×30cm×300cm",
    height: "300cm",
    material: "高分子PE+PE叶片",
    color: "翠绿色",
    isHot: true,
    isNew: false,
    inStock: true,
    customizable: true,
  },
  {
    id: "655698",
    sku: "655698",
    name: "迷你榕树 - 标准版",
    subtitle: "经济实惠，完美适配小型空间",
    nameEn: "Mini Ficus Tree Standard",
    price: 129,
    category: "mini-potted",
    subcategory: "ficus-series",
    tags: ["榕树", "迷你", "经济"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663392852100/CD7tjTbceR5unCtzt9q9hX/1aC7QJXC65sF_7f92d289.jpg",
    rating: 4.6,
    reviews: 215,
    description: "经济实惠的迷你榕树，完美适配小型空间。",
    features: ["高度仿真", "防晒防褪色", "易清洁"],
    size: "20cm×20cm×150cm",
    height: "150cm",
    material: "高分子PE+PE叶片",
    color: "翠绿色",
    isHot: true,
    isNew: false,
    inStock: true,
  },
  {
    id: "640602",
    sku: "640602",
    name: "红叶亮丽木 - 小型",
    subtitle: "色彩鲜艳，为空间增添活力",
    nameEn: "Croton Plant Small",
    price: 159,
    category: "mini-potted",
    subcategory: "colorful-plants",
    tags: ["红叶", "彩色", "小型"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663392852100/CD7tjTbceR5unCtzt9q9hX/CRuKkbG1dYF3_2789c9b7.jpg",
    rating: 4.7,
    reviews: 142,
    description: "色彩鲜艳的红叶亮丽木，叶片呈现红、黄、橙等多种颜色，为空间增添活力。",
    features: ["色彩丰富", "叶片逼真", "易清洁", "长期不褪色"],
    size: "25cm×25cm×100cm",
    height: "88-110cm",
    material: "高分子PE叶片",
    color: "红黄橙混合色",
    isHot: false,
    isNew: true,
    inStock: true,
  },
  {
    id: "250001",
    sku: "250001",
    name: "白玉兰 - 迷你版",
    subtitle: "优雅的白玉兰，花朵洁白无瑕",
    nameEn: "Magnolia Mini",
    price: 199,
    category: "mini-potted",
    subcategory: "flowering-plants",
    tags: ["白玉兰", "花卉", "迷你"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663392852100/CD7tjTbceR5unCtzt9q9hX/psqMzuYcuBt9_244cff3b.jpg",
    rating: 4.9,
    reviews: 287,
    description: "优雅的白玉兰，花朵洁白无瑕，散发高级气质。",
    features: ["花朵逼真", "香气模拟", "高端气质", "易清洁"],
    size: "25cm×25cm×160cm",
    height: "160cm",
    material: "高分子PE花朵+PE叶片",
    color: "白色+绿色",
    isHot: true,
    isNew: true,
    inStock: true,
    customizable: true,
  },

  // ========== 中型盆栽 ==========
  {
    id: "590606",
    sku: "590606",
    name: "发财树 - 中型",
    subtitle: "寓意吉祥，象征财运亨通",
    nameEn: "Fortune Tree Medium",
    price: 299,
    originalPrice: 399,
    category: "medium-potted",
    subcategory: "fortune-series",
    tags: ["发财树", "中型", "吉祥"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663392852100/CD7tjTbceR5unCtzt9q9hX/7C585YlSfRM4_483c7ec8.jpg",
    rating: 4.8,
    reviews: 456,
    description: "寓意吉祥的发财树，象征财运亨通。中型尺寸适合客厅、书房摆放。",
    features: ["寓意吉祥", "叶片翠绿", "易清洁", "商务赠礼首选"],
    size: "35cm×35cm×70cm",
    height: "70cm",
    material: "高分子PE叶片",
    color: "翠绿色",
    isHot: true,
    isNew: false,
    inStock: true,
    customizable: true,
  },
  {
    id: "590607",
    sku: "590607",
    name: "发财树 - 高级版",
    subtitle: "枝叶繁茂，气势恢宏",
    nameEn: "Fortune Tree Premium",
    price: 449,
    category: "medium-potted",
    subcategory: "fortune-series",
    tags: ["发财树", "高级", "繁茂"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663392852100/CD7tjTbceR5unCtzt9q9hX/F6JSFfToAfW8_6c7af10d.webp",
    rating: 4.9,
    reviews: 523,
    description: "高级发财树，枝叶繁茂，气势恢宏。适合大型客厅、办公室。",
    features: ["枝叶繁茂", "高度仿真", "易清洁", "商务首选"],
    size: "40cm×40cm×165cm",
    height: "165cm",
    material: "高分子PE叶片",
    color: "翠绿色",
    isHot: true,
    isNew: false,
    inStock: true,
    customizable: true,
  },
  {
    id: "231741",
    sku: "231741",
    name: "茉莉树",
    subtitle: "清香四溢，白色花朵精致优雅",
    nameEn: "Jasmine Tree",
    price: 279,
    category: "medium-potted",
    subcategory: "flowering-plants",
    tags: ["茉莉", "花卉", "中型"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663392852100/CD7tjTbceR5unCtzt9q9hX/KAJ3oEiOm4Jb_10de113a.webp",
    rating: 4.7,
    reviews: 198,
    description: "清香四溢的茉莉树，白色花朵精致优雅，为空间增添温暖气息。",
    features: ["花朵精致", "香气逼真", "易清洁", "优雅气质"],
    size: "30cm×30cm×160cm",
    height: "160cm",
    material: "高分子PE花朵+PE叶片",
    color: "白色+绿色",
    isHot: false,
    isNew: true,
    inStock: true,
  },
  {
    id: "898801",
    sku: "898801",
    name: "山茶树",
    subtitle: "高贵的山茶树，花朵绚烂多彩",
    nameEn: "Camellia Tree",
    price: 329,
    category: "medium-potted",
    subcategory: "flowering-plants",
    tags: ["山茶", "花卉", "高贵"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663392852100/CD7tjTbceR5unCtzt9q9hX/7UwKG3jUHr2F_60fde2b2.jpg",
    rating: 4.8,
    reviews: 267,
    description: "高贵的山茶树，花朵绚烂多彩，是空间的视觉焦点。",
    features: ["花朵绚烂", "高贵气质", "易清洁", "长期不褪色"],
    size: "35cm×35cm×180cm",
    height: "180cm",
    material: "高分子PE花朵+PE叶片",
    color: "红粉色+绿色",
    isHot: true,
    isNew: true,
    inStock: true,
  },

  // ========== 大型落地树 ==========
  {
    id: "655693",
    sku: "655693",
    name: "大型榕树 - 旗舰版",
    subtitle: "气势恢宏，枝叶茂密",
    nameEn: "Large Ficus Tree Flagship",
    price: 899,
    originalPrice: 1299,
    category: "large-floor",
    subcategory: "large-ficus",
    tags: ["榕树", "大型", "旗舰"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663392852100/CD7tjTbceR5unCtzt9q9hX/FxpFeDtrx79F_c7d6c414.jpg",
    rating: 4.9,
    reviews: 612,
    description: "气势恢宏的大型榕树，枝叶茂密，是客厅、大堂的绝佳装饰。采用高端仿真技术，叶片细节完美还原。",
    features: ["枝叶茂密", "高度仿真", "易清洁", "气势恢宏"],
    size: "60cm×60cm×240cm",
    height: "240cm",
    material: "高分子PE叶片+仿真树干",
    color: "深绿色",
    isHot: true,
    isNew: false,
    inStock: true,
    customizable: true,
  },
  {
    id: "655694",
    sku: "655694",
    name: "斑叶榕树 - 大型",
    subtitle: "叶片呈现绿白相间的斑纹",
    nameEn: "Variegated Ficus Tree Large",
    price: 799,
    category: "large-floor",
    subcategory: "large-ficus",
    tags: ["榕树", "斑叶", "大型"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663392852100/CD7tjTbceR5unCtzt9q9hX/kh15tiGYSFOi_89880ad9.png",
    rating: 4.8,
    reviews: 445,
    description: "叶片呈现绿白相间的斑纹，高贵典雅。适合高端住宅、商务空间。",
    features: ["叶片斑纹", "高贵典雅", "易清洁", "商务首选"],
    size: "50cm×50cm×170cm",
    height: "170cm",
    material: "高分子PE叶片",
    color: "绿白相间",
    isHot: true,
    isNew: false,
    inStock: true,
  },
  {
    id: "231602",
    sku: "231602",
    name: "红枣树 - 大型",
    subtitle: "独特的红枣树，充满生机活力",
    nameEn: "Red Jujube Tree Large",
    price: 749,
    category: "large-floor",
    subcategory: "specialty-trees",
    tags: ["红枣树", "大型", "独特"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663392852100/CD7tjTbceR5unCtzt9q9hX/aVjWmpXhboUr_598ff1cb.webp",
    rating: 4.7,
    reviews: 334,
    description: "独特的红枣树，枝条自然蜿蜒，红色果实点缀其间，充满生机活力。",
    features: ["果实逼真", "枝条自然", "易清洁", "独特气质"],
    size: "55cm×55cm×210cm",
    height: "210cm",
    material: "高分子PE果实+PE叶片",
    color: "绿色+红色",
    isHot: false,
    isNew: true,
    inStock: true,
  },

  // ========== 花瓶插花系列 ==========
  {
    id: "flower-001",
    sku: "FLOWER-001",
    name: "高端花艺组合 - 玫瑰系列",
    subtitle: "精选高端仿真玫瑰，打造高级花艺",
    nameEn: "Premium Rose Arrangement",
    price: 399,
    category: "flower-arrangement",
    subcategory: "rose-series",
    tags: ["玫瑰", "花艺", "高端"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663392852100/CD7tjTbceR5unCtzt9q9hX/xFhQ9CSUh3yz_5eb04e12.jpg",
    rating: 4.9,
    reviews: 298,
    description: "精选高端仿真玫瑰，配合绿叶和装饰花材，打造高级花艺作品。",
    features: ["花朵逼真", "高端气质", "易清洁", "永不凋谢"],
    size: "25cm×25cm×80cm",
    height: "80cm",
    material: "高分子PE花朵+丝绸叶片",
    color: "红色+绿色",
    isHot: true,
    isNew: true,
    inStock: true,
    customizable: true,
  },
  {
    id: "flower-002",
    sku: "FLOWER-002",
    name: "现代简约花艺 - 白色系",
    subtitle: "简约现代风格，百搭风格",
    nameEn: "Modern Minimalist White Arrangement",
    price: 349,
    category: "flower-arrangement",
    subcategory: "modern-series",
    tags: ["花艺", "现代", "白色"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663392852100/CD7tjTbceR5unCtzt9q9hX/qXKe77XN90tP_244adfc6.jpg",
    rating: 4.8,
    reviews: 212,
    description: "简约现代风格，白色和米色花材搭配，适合北欧、现代风格装修。",
    features: ["设计简约", "色彩清爽", "易清洁", "百搭风格"],
    size: "20cm×20cm×60cm",
    height: "60cm",
    material: "高分子PE花朵+丝绸叶片",
    color: "白色+米色",
    isHot: false,
    isNew: true,
    inStock: true,
  },

  // ========== 商业用高大乔木 ==========
  {
    id: "commercial-001",
    sku: "COMM-001",
    name: "商业用发财树 - 超大型",
    subtitle: "专为商业空间设计，气势恢宏",
    nameEn: "Commercial Fortune Tree XL",
    price: 2499,
    originalPrice: 3299,
    category: "commercial-trees",
    subcategory: "commercial-fortune",
    tags: ["发财树", "商业", "超大"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663392852100/CD7tjTbceR5unCtzt9q9hX/uMFc8TWjWdo4_8e8bea09.jpg",
    rating: 4.9,
    reviews: 156,
    description: "专为商业空间设计的超大型发财树，枝叶繁茂，气势恢宏。适合酒店大堂、商场、展厅。",
    features: ["超大尺寸", "气势恢宏", "易清洁", "商业首选"],
    size: "80cm×80cm×300cm",
    height: "300cm",
    material: "高分子PE叶片+仿真树干",
    color: "翠绿色",
    isHot: true,
    isNew: false,
    inStock: true,
    customizable: true,
  },
  {
    id: "commercial-002",
    sku: "COMM-002",
    name: "商业用大型榕树 - 双干",
    subtitle: "双干设计，更显气势",
    nameEn: "Commercial Large Ficus Tree Double Trunk",
    price: 1999,
    category: "commercial-trees",
    subcategory: "commercial-ficus",
    tags: ["榕树", "商业", "双干"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663392852100/CD7tjTbceR5unCtzt9q9hX/IrhvB1k4gO01_7a9ff68c.jpg",
    rating: 4.8,
    reviews: 134,
    description: "双干设计的大型榕树，更显气势。适合酒店、商场、写字楼大堂。",
    features: ["双干设计", "气势十足", "易清洁", "商务首选"],
    size: "70cm×70cm×250cm",
    height: "250cm",
    material: "高分子PE叶片+仿真树干",
    color: "深绿色",
    isHot: true,
    isNew: false,
    inStock: true,
    customizable: true,
  },

  // ========== 植物雕塑系列 ==========
  {
    id: "sculpture-001",
    sku: "SCULP-001",
    name: "大象造型绿植雕塑",
    subtitle: "创意十足，立体感强",
    nameEn: "Elephant Shaped Plant Sculpture",
    price: 3999,
    category: "plant-sculpture",
    subcategory: "animal-sculptures",
    tags: ["雕塑", "大象", "创意"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663392852100/CD7tjTbceR5unCtzt9q9hX/V4K2KmffJW0r_6d19d3ae.webp",
    rating: 4.9,
    reviews: 87,
    description: "创意十足的大象造型绿植雕塑，用仿真绿植打造立体大象形象。适合商业空间、主题乐园。",
    features: ["创意设计", "立体感强", "易清洁", "吸睛度高"],
    size: "150cm×100cm×200cm",
    height: "200cm",
    material: "高分子PE叶片+钢铁骨架",
    color: "绿色",
    isHot: true,
    isNew: true,
    inStock: true,
    customizable: true,
  },
  {
    id: "sculpture-002",
    sku: "SCULP-002",
    name: "几何造型绿植墙",
    subtitle: "现代几何造型，线条简洁",
    nameEn: "Geometric Plant Wall Sculpture",
    price: 2499,
    category: "plant-sculpture",
    subcategory: "geometric-sculptures",
    tags: ["雕塑", "几何", "现代"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663392852100/CD7tjTbceR5unCtzt9q9hX/0SCzobpS0M0g_e0ac0a50.webp",
    rating: 4.8,
    reviews: 65,
    description: "现代几何造型的绿植墙，线条简洁，适合现代办公室、展厅。",
    features: ["几何设计", "现代感强", "易清洁", "高端气质"],
    size: "120cm×30cm×180cm",
    height: "180cm",
    material: "高分子PE叶片+铝合金骨架",
    color: "绿色",
    isHot: false,
    isNew: true,
    inStock: true,
    customizable: true,
  },
];

export const advantages = [
  {
    title: "高度仿真",
    description: "采用最新高分子仿真技术，叶脉纹理、色彩层次完美还原真实植物，逼真度达99%。",
    icon: "🎨",
  },
  {
    title: "永不凋谢",
    description: "无需浇水、无需日照、无需修剪，一年四季保持最佳状态，无需担心植物枯萎。",
    icon: "♾️",
  },
  {
    title: "防晒防褪色",
    description: "采用UV防护技术，即使长期放在阳光下也不会褪色，色彩保持5年以上。",
    icon: "☀️",
  },
  {
    title: "易清洁维护",
    description: "只需定期用软布轻轻擦拭，无需专业养护知识，清洁简单方便。",
    icon: "🧹",
  },
  {
    title: "环保材料",
    description: "采用环保高分子材料，无毒无味，安全放心，适合家庭和商业场所使用。",
    icon: "🌍",
  },
  {
    title: "定制服务",
    description: "支持尺寸、颜色、造型定制，满足不同空间和风格需求，打造独特装饰。",
    icon: "✨",
  },
];

export const reviews: Review[] = [
  {
    id: "1",
    author: "张女士",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=1",
    rating: 5,
    content: "太棒了！这个发财树看起来和真的一样，朋友都以为我养的是真植物。质量非常好，已经放在客厅一个月了，没有任何褪色。",
    date: "2025-02-15",
    product: "发财树 - 中型",
    verified: true,
  },
  {
    id: "2",
    author: "李先生",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=2",
    rating: 5,
    content: "作为办公室装饰真的太合适了。不用担心植物枯死，省去了浇水的麻烦，而且看起来非常专业。推荐给所有办公室！",
    date: "2025-02-10",
    product: "迷你榕树 - 高级版",
    verified: true,
  },
  {
    id: "3",
    author: "王女士",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=3",
    rating: 5,
    content: "这个花艺组合真的很高级，放在客厅茶几上，整个空间都显得更有品味了。花朵的细节处理得非常好。",
    date: "2025-02-05",
    product: "高端花艺组合 - 玫瑰系列",
    verified: true,
  },
  {
    id: "4",
    author: "陈先生",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=4",
    rating: 4,
    content: "大型榕树很满意，就是有点重，搬运的时候费了点力气。但效果真的很棒，客厅立刻变得生机勃勃。",
    date: "2025-01-28",
    product: "大型榕树 - 旗舰版",
    verified: true,
  },
  {
    id: "5",
    author: "刘女士",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=5",
    rating: 5,
    content: "卧室放了一个小盆栽，每天看着都很舒服。不用浇水真的太方便了，推荐给所有懒人！",
    date: "2025-01-20",
    product: "白玉兰 - 迷你版",
    verified: true,
  },
  {
    id: "6",
    author: "周先生",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=6",
    rating: 5,
    content: "商业用的大型发财树超级棒！我们酒店大堂现在看起来高级多了，客人都夸赞我们的装修。",
    date: "2025-01-15",
    product: "商业用发财树 - 超大型",
    verified: true,
  },
];
